import { useQuery } from '@tanstack/react-query'
import { BellPlus, Building2, CalendarClock, CheckCircle2, ClipboardCheck, FileText, MapPin, PackageCheck, Pencil, Route, Users } from 'lucide-react'
import { Link } from 'react-router-dom'
import { PageHeader } from '@/components/layout/AppShell'
import { DataState } from '@/components/data/DataState'
import { dashboardApi, type DashboardData } from '../api/dashboardApi'
import { useAuth } from '@/features/auth/hooks/useAuth'

const friendlyEvent=(type:string,title:string)=>{const value=`${type} ${title}`.toLowerCase();if(value.includes('check-in')||value.includes('checkin')||value.includes('visitstarted'))return{label:'Visita iniciada',Icon:MapPin,tone:'orange'};if(value.includes('check-out')||value.includes('checkout')||value.includes('visitcompleted'))return{label:'Visita finalizada',Icon:Route,tone:'green'};if(value.includes('attachment')||value.includes('archivo'))return{label:'Archivo agregado',Icon:FileText,tone:'blue'};if(value.includes('note')||value.includes('nota'))return{label:'Nota agregada',Icon:Pencil,tone:'blue'};if(value.includes('reminder')&&value.includes('complet'))return{label:'Recordatorio completado',Icon:CheckCircle2,tone:'green'};if(value.includes('reminder'))return{label:'Recordatorio creado',Icon:BellPlus,tone:'orange'};return{label:'Cliente actualizado',Icon:Pencil,tone:'blue'}}
const dateTime=(value:string)=>{const date=new Date(value),today=new Date();const day=date.toLocaleDateString('en-CA')===today.toLocaleDateString('en-CA')?'Hoy':date.toLocaleDateString('es-BO',{day:'numeric',month:'short'});return `${day} · ${date.toLocaleTimeString('es-BO',{hour:'numeric',minute:'2-digit'})}`}

export function DashboardPage(){
 const {user}=useAuth(),query=useQuery({queryKey:['dashboard'],queryFn:dashboardApi.get,refetchInterval:60000}),metrics=query.data?.metrics
 const cards=metrics?[{label:'Clientes activos',value:metrics.activeCustomers,icon:Users},{label:'Proyectos activos',value:metrics.activeProjects,icon:Building2},{label:'Entregas pendientes',value:metrics.pendingDeliveries,icon:ClipboardCheck},{label:'Entregas vencidas',value:metrics.overdueDeliveries,icon:CalendarClock},{label:'Entregas del mes',value:metrics.completedDeliveriesThisMonth,icon:PackageCheck}]:[]
 return <main className="dashboard-content"><PageHeader eyebrow="Operación comercial" title={`Buenos días, ${user?.fullName.split(' ')[0]||'equipo'}`} description="Resumen actualizado de la operación."/><DataState loading={query.isLoading} error={query.error} isEmpty={!query.data} empty="No hay información disponible.">{query.data&&<><section className="real-metrics">{cards.map(({label,value,icon:Icon})=><article className="metric-card" key={label}><span className="metric-icon orange"><Icon/></span><div><p>{label}</p><strong>{value}</strong></div></article>)}</section><DashboardSections data={query.data}/></>}</DataState></main>
}

function SectionHeader({title,to,label}:{title:string;to:string;label:string}){return <header className="dashboard-section-header"><h2>{title}</h2><Link to={to}>{label} →</Link></header>}
function Empty({icon:Icon,title,text}:{icon:typeof PackageCheck;title:string;text:string}){return <div className="dashboard-empty"><span><Icon/></span><strong>{title}</strong><p>{text}</p></div>}

function DashboardSections({data}:{data:DashboardData}){
 return <section className="dashboard-real-grid operational-grid">
  <article className="activity-card dashboard-panel"><SectionHeader title="Actividad reciente" to="/reports" label="Ver toda"/>{data.recentActivity.length?<div className="dashboard-timeline">{data.recentActivity.slice(0,6).map((item,index)=>{const{label,Icon,tone}=friendlyEvent(item.eventTypeName,item.title);return <div className="dashboard-event" key={`${item.projectExternalId}-${item.occurredAtUtc}-${index}`}><span className={`dashboard-event-icon ${tone}`}><Icon/></span><div><strong>{label}</strong><small><Link to={`/projects?selected=${encodeURIComponent(item.projectExternalId)}`}>{item.projectName}</Link> · {item.userName||'Sistema'}</small><time title={new Date(item.occurredAtUtc).toLocaleString('es-BO')}>{dateTime(item.occurredAtUtc)}</time></div></div>})}</div>:<Empty icon={Route} title="Todavía no hay actividad" text="Los movimientos comerciales aparecerán aquí."/>}</article>
  <article className="activity-card dashboard-panel"><SectionHeader title="Entregas urgentes" to="/deliveries" label="Ver todas"/>{data.urgentDeliveries.length?<div className="dashboard-list">{data.urgentDeliveries.map(item=><Link className="dashboard-list-row" to={`/deliveries?selected=${encodeURIComponent(item.deliveryExternalId)}`} key={item.deliveryExternalId}><span className={`list-icon ${item.isOverdue?'danger':'warning'}`}><PackageCheck/></span><div><strong>{item.projectName}</strong><small>{new Date(item.committedDateUtc).toLocaleDateString('es-BO',{dateStyle:'medium'})}</small></div><em className={item.isOverdue?'overdue':''}>{item.statusName}</em></Link>)}</div>:<Empty icon={PackageCheck} title="No hay entregas urgentes" text="Todo está al día por ahora."/>}</article>
  <article className="activity-card dashboard-panel"><SectionHeader title="Próximos seguimientos" to="/reminders" label="Ver todos"/>{data.upcomingFollowUps.length?<div className="dashboard-list">{data.upcomingFollowUps.map(item=><Link className="dashboard-list-row" to={`/customers?selected=${encodeURIComponent(item.customerExternalId)}`} key={item.reminderExternalId}><span className="list-icon warning"><CalendarClock/></span><div><strong>{item.text}</strong><small>{item.customerName} · {item.assignedToName}</small><time>{dateTime(item.reminderAtUtc)}</time></div></Link>)}</div>:<Empty icon={CalendarClock} title="No tienes seguimientos pendientes" text="Los próximos recordatorios aparecerán aquí."/>}</article>
  <article className="activity-card dashboard-panel"><SectionHeader title="Avance de proyectos" to="/projects" label="Ver todos"/>{data.projectLocations.length?<div className="project-progress-list">{data.projectLocations.slice(0,5).map(item=><Link to={`/projects?selected=${encodeURIComponent(item.projectExternalId)}`} key={item.projectExternalId}><div><strong>{item.name}</strong><span>{item.progressPercentage}%</span></div><small>{item.customerName||item.address||'Sin cliente asociado'}</small><progress max="100" value={item.progressPercentage}/></Link>)}</div>:<Empty icon={Building2} title="No hay proyectos activos" text="El avance de tus obras aparecerá aquí."/>}</article>
 </section>
}
