import { Bell, Building2, CalendarDays, ChevronRight, ClipboardCheck, LayoutDashboard, LogOut, MapPinned, Menu, Route, Search, Users } from 'lucide-react'
import { Link } from 'react-router-dom'
import type { AuthUser } from '@/features/auth/types/authTypes'
import { Brand } from '@/presentation/components/Brand'

const navigation = [{ label: 'Resumen', path: '/', icon: LayoutDashboard, permission: 'dashboard.read' }, { label: 'Clientes', path: '/customers', icon: Users, permission: 'customers.read' }, { label: 'Proyectos', path: '/projects', icon: Building2, permission: 'projects.read' }, { label: 'Productos', path: '/catalog', icon: ClipboardCheck, permission: 'products.read' }, { label: 'Jornadas', path: '/operations', icon: CalendarDays, permission: 'visits.read' }, { label: 'Rutas', path: '/operations', icon: Route, permission: 'visits.read' }]
const metrics = [{ label: 'Vendedores activos', value: '8', note: 'de 10 vendedores', icon: Users, tone: 'blue' }, { label: 'Visitas de hoy', value: '24', note: '16 completadas', icon: ClipboardCheck, tone: 'orange' }, { label: 'Proyectos en seguimiento', value: '31', note: '5 requieren atención', icon: Building2, tone: 'violet' }]
const activities = [['08:32','Carlos Méndez','inició jornada','Equipetrol'],['09:10','Andrea Flores','registró una visita','Constructora Vértice'],['10:45','Luis Rojas','finalizó visita','Edificio Ventura']]

export function DashboardPage({ user, onLogout }: { user: AuthUser; onLogout: () => void | Promise<void> }) {
  const firstName = user.fullName?.split(' ')[0] || 'equipo'; const initials = user.fullName?.split(' ').slice(0, 2).map(part => part[0]).join('').toUpperCase() || 'UT'
  const allowedNavigation = navigation.filter(item => user.permissions.some(permission => permission.toLowerCase() === item.permission))
  return <div className="dashboard"><aside className="dashboard-sidebar"><Brand inverse/><p className="nav-label">Operación</p><nav>{allowedNavigation.map(({ label, path, icon: Icon }, index) => <Link to={path} className={index === 0 ? 'active' : ''} key={label}><Icon/><span>{label}</span></Link>)}</nav><button className="logout" onClick={() => void onLogout()}><LogOut/>Cerrar sesión</button></aside><section className="dashboard-body"><header className="topbar"><button className="menu-button" aria-label="Abrir menú"><Menu/></button><div className="search"><Search/><input placeholder="Buscar en UrbanTrack"/></div><div className="profile"><button aria-label="Notificaciones" className="notification"><Bell/><i/></button><span className="avatar">{initials}</span><div><strong>{user.fullName}</strong><small>{user.company.name}</small></div></div></header><main className="dashboard-content"><div className="heading-row"><div><p className="overline">Operación comercial</p><h1>Buenos días, {firstName}</h1><p>Aquí tienes el resumen de la operación de hoy.</p><p className="permission-summary">{user.permissions.length} permisos activos</p></div><button className="map-button"><MapPinned/>Ver mapa de vendedores</button></div><section className="metrics">{metrics.map(({ label, value, note, icon: Icon, tone }) => <article className="metric-card" key={label}><span className={`metric-icon ${tone}`}><Icon/></span><div><p>{label}</p><strong>{value}</strong><small>{note}</small></div></article>)}</section><section className="dashboard-grid"><article className="activity-card"><header><div><h2>Actividad de hoy</h2><p>Seguimiento en tiempo real del equipo</p></div><button>Ver todo</button></header>{activities.map((row, index) => <div className="activity" key={row[0]}><time>{row[0]}</time><div><strong>{row[1]} <span>{row[2]}</span></strong><small>{row[3]}</small></div><em className={index === 2 ? 'done' : ''}>{index === 2 ? 'Completada' : 'En curso'}</em></div>)}</article><article className="route-card"><Route/><h2>Equipo en ruta</h2><p>8 vendedores tienen una jornada activa en este momento.</p><div className="avatar-row">{['CM','AF','LR','MV','JP'].map(name => <span className="avatar" key={name}>{name}</span>)}</div><button>Abrir seguimiento <ChevronRight/></button></article></section></main></section></div>
}
