import { useState, type FormEvent } from 'react'
import { ChevronRight, Eye, EyeOff, ShieldCheck } from 'lucide-react'
import { Link, useLocation, useNavigate } from 'react-router-dom'
import { useAuth } from '@/features/auth/hooks/useAuth'
import { AppError } from '@/lib/api/apiError'
import { Brand } from '@/presentation/components/Brand'

export function LoginPage() {
  const auth = useAuth(); const navigate = useNavigate(); const location = useLocation()
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [visible, setVisible] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  const state = location.state as { from?: string; sessionExpired?: boolean } | null
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(''); try { await auth.login({ email, password }); navigate(state?.from ?? '/', { replace: true }) } catch (reason) { setError(reason instanceof AppError || reason instanceof Error ? reason.message : 'Ocurrió un error inesperado.') } finally { setBusy(false) } }
  return <main className="login-page"><section className="login-hero"><div className="orb orb-one"/><div className="orb orb-two"/><Brand inverse/><div className="hero-copy"><span className="pill">Gestión comercial en movimiento</span><h1>Tu operación,<br/>siempre en ruta.</h1><p>Organiza clientes, obras, jornadas y visitas desde un solo lugar. Con información clara para decidir a tiempo.</p><div className="security-note"><span><ShieldCheck/></span><div><strong>Acceso seguro</strong><small>Tu información protegida y disponible para tu equipo.</small></div></div></div><small className="copyright">© 2026 UrbanTrack. Todos los derechos reservados.</small></section><section className="login-form-panel"><div className="login-form-wrap"><div className="mobile-brand"><Brand/></div><p className="overline">Bienvenido</p><h2>Inicia sesión</h2><p className="subtitle">Ingresa con las credenciales asignadas a tu cuenta.</p>{state?.sessionExpired && <p className="form-notice">Tu sesión expiró. Inicia sesión nuevamente.</p>}<form onSubmit={submit}><label htmlFor="email">Correo electrónico</label><input id="email" type="email" autoComplete="email" value={email} onChange={event => setEmail(event.target.value)} placeholder="nombre@empresa.com"/><div className="password-label"><label htmlFor="password">Contraseña</label><Link to="/forgot-password">¿Olvidaste tu contraseña?</Link></div><div className="password-input"><input id="password" type={visible ? 'text' : 'password'} autoComplete="current-password" value={password} onChange={event => setPassword(event.target.value)}/><button type="button" aria-label={visible ? 'Ocultar contraseña' : 'Mostrar contraseña'} onClick={() => setVisible(!visible)}>{visible ? <EyeOff/> : <Eye/>}</button></div>{error && <p className="form-error" role="alert">{error}</p>}<button className="primary-button" disabled={busy}>{busy ? 'Ingresando…' : 'Ingresar'}{!busy && <ChevronRight/>}</button></form><p className="help">¿Necesitas ayuda? <strong>Contacta a soporte</strong></p></div></section></main>
}
